// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Telefon_Sutunu_Kullaniciya_Eklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Telefon_Sutunu_Kullaniciya_Eklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "201812020837156_Telefon_Sutunu_Kullaniciya_Eklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
