// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ShowOnHomePage_added_to_Product_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShowOnHomePage_added_to_Product_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201812230845015_ShowOnHomePage_added_to_Product_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
