// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Viewed_column_added_to_urun_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Viewed_column_added_to_urun_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201901190850502_Viewed_column_added_to_urun_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
