// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class slideshow_table_product_and_categories_sort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slideshow_table_product_and_categories_sort));
        
        string IMigrationMetadata.Id
        {
            get { return "201901130711408_slideshow_table_product_and_categories_sort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
