// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class blog_table_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blog_table_created));
        
        string IMigrationMetadata.Id
        {
            get { return "201901130816072_blog_table_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
