// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_free_shipping_areas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_free_shipping_areas));
        
        string IMigrationMetadata.Id
        {
            get { return "201902230729129_added_free_shipping_areas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
