// <auto-generated />
namespace ETicaret.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tags_column_added_to_blog_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tags_column_added_to_blog_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201901200816489_Tags_column_added_to_blog_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
